create table Zipcodes (
	zip_code varchar(50)
	, latitude varchar(50)
	, longitude varchar(50)
	, city_name varchar(50)
	, state_id varchar(50)
	, state_name varchar(50)
	, zcta varchar(50)
	, [population] varchar(50)
	, density varchar(50)
	, county_fips varchar(50)
	, county_name varchar(50)
--	, all_county_weights varchar(50)
--	, imprecise varchar(50)
--	, military varchar(50)
	, timezone varchar(100)
)